### ISSUE TITLE
Issue with cell formatting

### ISSUE THREAD

**Issue by leduy99** [rentiansheng/xlsx#12]
I have this code to fill each odd row and even row with 2 different color
```
if i%2 == 1 {
			style = xlsx.NewStyle()
			style.Fill = *xlsx.NewFill("none", "FFFFFFFF", "00000000")
		} else {
			style = xlsx.NewStyle()
			style.Fill = *xlsx.NewFill("solid", "d0d0d0", "d0d0d0")
		}
```
But as far as I know, If there is no reset with xlsx.NewStyle(), the code won't work, for example:
```
if i%2 == 1 {
			style.Fill = *xlsx.NewFill("none", "FFFFFFFF", "00000000")
		} else {
			style.Fill = *xlsx.NewFill("solid", "d0d0d0", "d0d0d0")
		}
```
If I use cell.SetStyle(style) then the row will just have no fill. This made me tired 'cause the NewStyle also reset all my font and border setting and i have to set things up again. Can anyone provide solution for this? thank you

**Comment by rentiansheng** [comment]
Hi, 


I didn't understand your question. Can you describe the specific details?
If you only want to modify the partial values of the cell's style, you can use cell.GetStyle() to get the style that the cell already has, and then reassign it.

**Comment by rentiansheng** [comment]
@leduy99
